# Generated by Django 2.1.14 on 2020-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
                ('link', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
