# Generated by Django 2.1.14 on 2020-01-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20200124_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
