# Generated by Django 2.1.14 on 2020-01-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20200124_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='type',
        ),
        migrations.AddField(
            model_name='component',
            name='type_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.TypeOfComponent'),
            preserve_default=False,
        ),
    ]
